"""Generate tools/API.md, the compact API card of the modelling kits.

The Builder reads the card (about 3 k tokens) instead of the modules
(about 17 k). It is built from the source with `ast`, so it never drifts:
every public function and class of the kit modules with its signature and
the first sentence of its docstring, plus the module docstring's first
paragraph.

    python tools/api_card.py            # rewrites tools/API.md
    python tools/api_card.py --check    # exit 1 if API.md is out of date

Provenance: proposed in the experiment 14 Fable run context audit.
"""
import ast
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
MODULES = ["craftbot_lib", "geometry2d", "planes", "ruled", "framing", "sheathing"]
HARNESS = ["render_views", "check_overlaps", "check_contacts", "triage", "closeout",
           "export_all_models", "layers", "callouts", "api_card"]
OUT = os.path.join(HERE, "API.md")


def first_sentence(doc):
    if not doc:
        return ""
    text = " ".join(doc.strip().split())
    for stop in (". ", ".\n"):
        if stop in text:
            return text[:text.index(stop) + 1]
    return text if text.endswith(".") else text + "."


def first_paragraph(doc):
    if not doc:
        return ""
    return " ".join(doc.strip().split("\n\n")[0].split())


def signature(fn):
    a = fn.args
    parts = []
    pos = a.posonlyargs + a.args
    defaults = [None] * (len(pos) - len(a.defaults)) + list(a.defaults)
    for arg, d in zip(pos, defaults):
        parts.append(arg.arg if d is None else f"{arg.arg}={ast.unparse(d)}")
    if a.vararg:
        parts.append("*" + a.vararg.arg)
    for arg, d in zip(a.kwonlyargs, a.kw_defaults):
        parts.append(arg.arg if d is None else f"{arg.arg}={ast.unparse(d)}")
    if a.kwarg:
        parts.append("**" + a.kwarg.arg)
    return f"{fn.name}({', '.join(parts)})"


def module_card(name, full):
    path = os.path.join(HERE, name + ".py")
    tree = ast.parse(open(path, encoding="utf-8").read())
    lines = [f"### `{name}.py`", "", first_paragraph(ast.get_docstring(tree) or "") or "(no module docstring)", ""]
    if not full:
        return lines + [""]
    for node in tree.body:
        if isinstance(node, ast.FunctionDef) and not node.name.startswith("_"):
            lines.append(f"- `{signature(node)}`: {first_sentence(ast.get_docstring(node))}")
        elif isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
            lines.append(f"- class `{node.name}`: {first_sentence(ast.get_docstring(node))}")
            for sub in node.body:
                if isinstance(sub, ast.FunctionDef) and not sub.name.startswith("_"):
                    lines.append(f"  - `{signature(sub)}`: {first_sentence(ast.get_docstring(sub))}")
    lines.append("")
    return lines


def build():
    out = ["# tools/ API card", "",
           "Generated by `python tools/api_card.py` from the module docstrings and signatures; do not edit by hand.",
           "Read this instead of the modules. Open a module only for the body of one function you need to extend.", "",
           "Conventions every kit enforces: every solid is convex (a bird's mouth is body + tail, a wall with a hole is",
           "pieces), prisms are wound outward, `place_element` replaces a same-named object (name with every loop index),",
           "collection names are global in Blender (hide lists use the bare child name).", "",
           "## Modelling kits (import from an experiment script)", ""]
    for m in MODULES:
        out += module_card(m, True)
    out += ["## Harness scripts (run from the repo root)", ""]
    for m in HARNESS:
        if os.path.isfile(os.path.join(HERE, m + ".py")):
            out += module_card(m, False)
    return "\n".join(out).rstrip() + "\n"


def main():
    text = build()
    if "--check" in sys.argv:
        current = open(OUT, encoding="utf-8").read() if os.path.isfile(OUT) else ""
        if current != text:
            print("tools/API.md is out of date: run python tools/api_card.py")
            sys.exit(1)
        print("tools/API.md is current")
        return
    open(OUT, "w", encoding="utf-8", newline="\n").write(text)
    print(f"wrote {os.path.relpath(OUT, os.getcwd())} ({len(text)} chars)")


if __name__ == "__main__":
    main()
