"""Generate tools/API.md, the compact API card of the modelling kits.

The Builder reads the card (about 3 k tokens) instead of the modules
(about 17 k). It is built from the source with `ast`, so it never drifts:
every public function and class of the kit modules with its signature and
the first sentence of its docstring, plus the module docstring's first
paragraph.

    python tools/api_card.py            # rewrites tools/API.md and tools/API_FABRICATION.md
    python tools/api_card.py --check    # exit 1 if either card is out of date

The fabrication kit has its own card, API_FABRICATION.md, so the Builder's
card stays short; API.md only names those modules.

Provenance: proposed in the experiment 14 Fable run context audit.
"""
import ast
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
MODULES = ["craftbot_lib", "geometry2d", "planes", "ruled", "framing", "sheathing"]
HARNESS = ["render_views", "sheet_png", "check_overlaps", "check_contacts", "check_bearing", "triage", "closeout",
           "export_all_models", "layers", "callouts", "api_card"]
# Fabrication kit: runs without Blender on members.json (export_members.py writes it from Blender).
FABRICATION = ["export_members", "cutlist", "drafting", "title_blocks", "hidden_lines", "vector_pdf", "qr_code", "drawing_assets",
               "fonts", "newsprint", "organigram"]
OUT = os.path.join(HERE, "API.md")
OUT_FABRICATION = os.path.join(HERE, "API_FABRICATION.md")


def first_sentence(doc):
    if not doc:
        return ""
    text = " ".join(doc.strip().split())
    for stop in (". ", ".\n"):
        if stop in text:
            return text[:text.index(stop) + 1]
    return text if text.endswith(".") else text + "."


def first_paragraph(doc):
    if not doc:
        return ""
    return " ".join(doc.strip().split("\n\n")[0].split())


def signature(fn):
    a = fn.args
    parts = []
    pos = a.posonlyargs + a.args
    defaults = [None] * (len(pos) - len(a.defaults)) + list(a.defaults)
    for arg, d in zip(pos, defaults):
        parts.append(arg.arg if d is None else f"{arg.arg}={ast.unparse(d)}")
    if a.vararg:
        parts.append("*" + a.vararg.arg)
    for arg, d in zip(a.kwonlyargs, a.kw_defaults):
        parts.append(arg.arg if d is None else f"{arg.arg}={ast.unparse(d)}")
    if a.kwarg:
        parts.append("**" + a.kwarg.arg)
    return f"{fn.name}({', '.join(parts)})"


def module_card(name, full):
    path = os.path.join(HERE, name + ".py")
    tree = ast.parse(open(path, encoding="utf-8").read())
    lines = [f"### `{name}.py`", "", first_paragraph(ast.get_docstring(tree) or "") or "(no module docstring)", ""]
    if not full:
        return lines + [""]
    for node in tree.body:
        if isinstance(node, ast.FunctionDef) and not node.name.startswith("_"):
            lines.append(f"- `{signature(node)}`: {first_sentence(ast.get_docstring(node))}")
        elif isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
            init = next((sub for sub in node.body if isinstance(sub, ast.FunctionDef) and sub.name == "__init__"), None)
            args = signature(init)[len("__init__(self"):-1].lstrip(", ") if init else ""
            lines.append(f"- class `{node.name}({args})`: {first_sentence(ast.get_docstring(node))}")
            for sub in node.body:
                if isinstance(sub, ast.FunctionDef) and not sub.name.startswith("_"):
                    lines.append(f"  - `{signature(sub)}`: {first_sentence(ast.get_docstring(sub))}")
    lines.append("")
    return lines


def build():
    out = ["# tools/ API card", "",
           "Generated by `python tools/api_card.py` from the module docstrings and signatures; do not edit by hand.",
           "Read this instead of the modules. Open a module only for the body of one function you need to extend.", "",
           "Conventions every kit enforces: every solid is convex (a bird's mouth is body + tail, a wall with a hole is",
           "pieces), prisms are wound outward, `place_element` replaces a same-named object (name with every loop index),",
           "collection names are global in Blender (hide lists use the bare child name).", "",
           "## Modelling kits (import from an experiment script)", ""]
    for m in MODULES:
        out += module_card(m, True)
    out += ["## Fabrication kit (not used in an experiment run; signatures in API_FABRICATION.md)", ""]
    for m in FABRICATION:
        out += module_card(m, False)
    out += ["## Harness scripts (run from the repo root)", ""]
    for m in HARNESS:
        if os.path.isfile(os.path.join(HERE, m + ".py")):
            out += module_card(m, m == "check_bearing")
    return "\n".join(out).rstrip() + "\n"


def build_fabrication():
    out = ["# tools/ fabrication kit API card", "",
           "Generated by `python tools/api_card.py` from the module docstrings and signatures; do not edit by hand.",
           "Read this instead of the modules. `skills/draft-fabrication-plans` says when and in what order to use them.", "",
           "Everything is in model millimetres (real metres x 1000 / scale). Members are convex, wound outwards and do",
           "not intersect; `export_members.py` needs Blender, the rest runs on its members.json without it.", "",
           "members.json is `{scale, stick_length, <extra keys>, members}`; a member is `{name, group (collection path),",
           "layer (viewer layer), stock ('3x5' = thickness x face in mm, or null for a part not cut from sticks), verts,",
           "faces}`. `drafting` exports the axes `X`, `Y`, `Z` (lists) and `vector_pdf` the papers `A2`, `A3` (portrait,",
           "mm) and the line weights `FINE` (dimension lines, leaders, datums), `THIN`, `MEDIUM`, `HEAVY`. A view is given by its `right` and `up` axes; the viewer",
           "stands at cross(right, up), so `Drawing(members, X, Z)` is the elevation seen from -y and `X, Y` the plan.", ""]
    for m in FABRICATION:
        out += module_card(m, True)
    return "\n".join(out).rstrip() + "\n"


def main():
    cards = [(OUT, build()), (OUT_FABRICATION, build_fabrication())]
    if "--check" in sys.argv:
        stale = [path for path, text in cards
                 if not os.path.isfile(path) or open(path, encoding="utf-8").read() != text]
        for path in stale:
            print(f"tools/{os.path.basename(path)} is out of date: run python tools/api_card.py")
        if stale:
            sys.exit(1)
        print("tools/API.md and tools/API_FABRICATION.md are current")
        return
    for path, text in cards:
        open(path, "w", encoding="utf-8", newline="\n").write(text)
        print(f"wrote {os.path.relpath(path, os.getcwd())} ({len(text)} chars)")


if __name__ == "__main__":
    main()
